epiphany-platform/CommonDataLayer

- docs/Getting-Started.md
Link on develop branch doesn't work for me... so I fixed this
> Fix k8s documentation link

- .gitignore
- Cargo.lock
- schema-registry/Cargo.toml
- schema-registry/src/db.rs
- schema-registry/src/error.rs
- schema-registry/src/lib.rs
- schema-registry/src/main.rs
- schema-registry/src/replication/mod.rs
- schema-registry/src/rpc.rs
- schema-registry/src/schema.rs
- schema-registry/src/types.rs
- schema-registry/src/types/storage/edges.rs
- schema-registry/src/types/storage/vertices.rs
> feat(schema-registry): add methods for exporting and importing all data from DB to json

- .dockerignore
- bin.Dockerfile
- workspace.Dockerfile
Reverts epiphany-platform/CommonDataLayer#33
Issues with this PR:
https://github.com/epiphany-platform/CommonDataLayer/pull/33#issuecomment-734779257
> Revert "Streamline dockerfile"

- .github/CODEOWNERS
- .github/workflows/publish-head.yml
It should create a docker image tagged as `:develop`
> feat(ci): add `develop` build + add me as codeowner

- docs/architecture.md
- docs/data_router.md
- docs/query_router.md
- docs/query_service.md
- docs/schema_registry.md
- tests/command_service/test_postgres_insertion.py
- tests/data/command_service/multiple_inserts.json
- tests/data/command_service/single_insert.json
It fixes component test data to comply with recent format change. Also, I've touched documentation a bit.
> fix: adjust json format in tests

- examples/deploy/docker-compose.yml
- query-service-ts/src/victoria.rs
- rpc/proto/query_service_ts.proto
- rpc/src/query_service_ts.rs
> feat(query-service-ts): Added raw queries support for VictoriaMetrics

- .github/workflows/check-docs.yml
- docs/getting_started.md
- docs/schema_registry.md
I think we can find this handy
> ci: add markdown link check workflow

- deployment/helm/cdl/charts/druid-timeseries/templates/command-service.yaml
- deployment/helm/cdl/charts/victoria-metrics-timeseries/templates/command-service.yaml
- deployment/helm/cdl/values-local.yaml
- deployment/helm/cdl/values.yaml
- deployment/helm/infrastructure/values.yaml
same queue/exchange/topic names for local deployments with kafka and rabbitmq
> refactor: local deployment, helm variables unification

- docs/rfc/CDLF-00010-00-rfc-01.md
[rendered](https://github.com/epiphany-platform/CommonDataLayer/blob/rfc/cim-versioning/docs/rfc/protocol_version.md)
Related thread: https://github.com/epiphany-platform/CommonDataLayer/discussions/239
> rfc: propose cdl input message versioning

- build.sh
> fix: build script fix

- .cargo/config.toml
- .github/workflows/test-deployment.yml
- crates/cdl-cli/src/args.rs
- crates/rpc/Cargo.toml
- crates/schema-registry/migrations/20210215170655_init-db.sql
- crates/schema-registry/src/main.rs
- crates/utils/src/communication/consumer.rs
- crates/utils/src/communication/publisher.rs
- crates/utils/src/status_endpoints.rs
- deployment/helm/infrastructure/templates/pgInit.yml
- deployment/helm/infrastructure/values.yaml
- tests/run-tests.sh
> something something dark side

- .github/workflows/publish.yml
* edge-registry
* partial-update-engine
* object-builder
* materializer
> ci: Publish docker images for materialization

- crates/query-router/src/error.rs
- crates/query-router/src/handler.rs
> fix: Query multiple returns error for timeseries

- Cargo.lock
- crates/api/src/main.rs
- crates/api/src/schema/query.rs
- crates/command-service/src/input/service/mod.rs
- crates/data-router/src/main.rs
- crates/edge-registry/src/main.rs
- crates/object-builder/src/main.rs
- crates/query-router/src/main.rs
- crates/utils/Cargo.toml
- crates/utils/src/communication/parallel_consumer.rs
- crates/utils/src/communication/publisher.rs
- crates/utils/src/tracing.rs
- crates/utils/src/tracing/http.rs
* Remove bug: std::process:abort()
* Add tokio::time::sleep on exit
Waits for #408
> chore: Add opentelemetry for HTTP warp servers

- crates/utils/src/communication/consumer.rs
> fix: Consumer logs error and continues

- .github/workflows/publish-nightly.yml
- .github/workflows/publish.yml
> fix: publish nightly action update

- crates/schema-registry/sqlx-data.json
- crates/schema-registry/src/db.rs
- crates/schema-registry/src/rpc.rs
> fix: Add materializer_options column in INSERT view

- crates/partial-update-engine/src/main.rs
> fix: PartialNotification format in PUE

- crates/api/src/schema/mutation.rs
- crates/api/src/types/view.rs
> fix: API uses JSON for view fields

- .cdl/development/query-service.toml
- crates/rpc/proto/schema_registry.proto
- crates/rpc/src/codegen/schema_registry.rs
- crates/rpc/src/schema_registry/types.rs
- crates/utils/src/communication/parallel_consumer.rs
- crates/utils/src/types/materialization.rs
- deployment/compose/README.md
- deployment/compose/docker-compose.yml
- deployment/compose/setup.sh
- deployment/compose/setup/configuration/api.toml
- deployment/compose/setup/configuration/command-service.toml
- deployment/compose/setup/configuration/data-router.toml
- deployment/compose/setup/configuration/default.toml
- deployment/compose/setup/configuration/schema-registry.toml
- deployment/compose/setup/schema_registry/initial-schema.grpc.json
- docs/configuration/query-service-ts.md
- docs/configuration/query-service.md
- examples/python-cdl/cli.py
- tests/common/query_service.py
- tests/data/object_builder/initial-schema.kafka.json
.NET protobuf codegen uses `Equals` as a method name, therefore there is a clash :/
> fix: Equals -> EqualsOp for .NET compability

- Cargo.lock
- crates/api/src/main.rs
- crates/api/src/schema/context.rs
- crates/api/src/schema/mutation.rs
- crates/api/src/schema/query.rs
- crates/api/src/schema/utils.rs
- crates/object-builder/src/lib.rs
- crates/rpc/Cargo.toml
- crates/rpc/proto/schema_registry.proto
- crates/rpc/src/codegen/schema_registry.rs
- crates/rpc/src/edge_registry.rs
- crates/rpc/src/materializer_ondemand.rs
- crates/rpc/src/schema_registry.rs
- crates/schema-registry/src/rpc.rs
I'm removing some code duplication via this PR
> chore: remove code duplication of bb8 pool

- .github/workflows/test-unit.yml
- Cargo.lock
- crates/api/src/schema/mutation.rs
- crates/api/src/types/view/input.rs
- crates/api/src/types/view/queried.rs
- crates/cdl-cli/src/actions/view.rs
- crates/dto/Cargo.toml
- crates/dto/src/lib.rs
- crates/dto/src/materialization.rs
- crates/object-builder/src/lib.rs
- crates/schema-registry/src/rpc.rs
- crates/utils/crates/rpc_dto/Cargo.toml
- crates/utils/crates/rpc_dto/src/attrs.rs
- crates/utils/crates/rpc_dto/src/lib.rs
- crates/utils/crates/rpc_dto/src/try_from_rpc.rs
- crates/utils/crates/rpc_dto/src/try_into_rpc.rs
> chore: Proc macro to derive from_rpc and into_rpc

- .github/workflows/test-unit.yml
- Dockerfile.e2e
- e2e/Cargo.toml
- e2e/src/lib.rs
> feat: hide e2e tests under feature flag

- crates/api/src/schema/mutation.rs
- web-admin/src/generated/graphql.ts
- web-admin/src/pages/insert/MessageForm.svelte
Closes https://github.com/epiphany-platform/CommonDataLayer/issues/595
> fix: Ensure web-admin sends version when inserting data to data-router

- docs/features/index.md
Leftovers from last PR -  #596.
> docs: feature list update

- .github/workflows/publish-nightly.yml
missing " in the script made it fail
> chore: fixed nightly publish script

- crates/object-builder/src/row_builder.rs
- crates/object-builder/src/view_plan/builder.rs
Not a breaking change: Only changing the content of error messages,
following code that was already merged to develop
> fix: Array -> SubObject in the string.
